name: IO Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  io-test:
    runs-on: self-hosted

    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      PROJECT: chuckaude-insecure-bank
      #BRANCH: ${GITHUB_REF##*/}
      BRANCH: master
      BLDCMD: mvn -B package -DskipTests

    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Synopsys Intelligent Security Scan
      id: prescription
      uses: synopsys-sig/intelligent-security-scan@v1
      with:
        ioServerUrl: ${{secrets.IO_SERVER_URL}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        additionalWorkflowArgs: --persona=developer --release.type=minor --sast.rescan.threshold=10  --sca.rescan.threshold=10 --file.change.threshold=20
                  --polaris.url=${{secrets.POLARIS_SERVER_URL}} --polaris.token=${{secrets.POLARIS_ACCESS_TOKEN}}
                  --sensitive.package.pattern='.*(.xml)$'
        stage: "IO"

    - name: Polaris Scan
      if: ${{steps.prescription.outputs.sastScan == 'true' }}
      run: |
        echo "Run a Polaris Scan"

    - name: Black Duck Scan
      if: ${{steps.prescription.outputs.scaScan == 'true' }}
      run: |
        echo "Run a Black Duck Scan"
