name: Polaris SAST

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  polaris:
    runs-on: maven:3-jdk-8
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      PROJECT: chuckaude-insecure-bank
      BLDCMD: mvn -B package -DskipTests
    steps:
    - uses: actions/checkout@v2
    - name: Polaris Scan
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris --co project.name=$PROJECT analyze -w -- $BLDCMD
