name: Polaris + Black Duck with IO

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  polaris-blackduck-io:
    runs-on: self-hosted

    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      PROJECT: chuckaude-insecure-bank
      BRANCH: ${GITHUB_REF##*/}
      BLDCMD: mvn -B package -DskipTests

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Synopsys Intelligent Security Scan
      id: prescription
      uses: synopsys-sig/intelligent-security-scan@v1.0.3
      with:
        ioServerUrl: ${{secrets.IO_SERVER_URL}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        additionalWorkflowArgs: --persona=developer --release.type=major --sast.rescan.threshold=5  --sca.rescan.threshold=5
                  --polaris.url=${{secrets.POLARIS_SERVER_URL}} --polaris.token=${{secrets.POLARIS_ACCESS_TOKEN}} 
                  --sensitive.package.pattern='.*(\\+\\+\\+.*(com\\/example\\/app)).*'
        stage: "IO"

    - name: Polaris Scan
      if: ${{steps.prescription.outputs.sastScan == 'true' }}
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris --co project.name=$PROJECT analyze -w -- $BLDCMD

    - name: Black Duck Scan
      if: ${{steps.prescription.outputs.scaScan == 'true' }}
      uses: blackducksoftware/github-action@v2
      with:
         args: --blackduck.url=${{secrets.BLACKDUCK_URL}} --blackduck.api.token=${{secrets.BLACKDUCK_TOKEN}} --detect.tools=SIGNATURE_SCAN,DETECTOR 
            --detect.project.name=$PROJECT --detect.project.version.name=$BRANCH
